title: ğ–â‹…ğ–†ğ–’â‹…ğ–‹ğ–”ğ–Œâ‹…ğ–‹ğ–ğ–˜ğ–
baseurl: ""
url: "https://i.am.fog.fish"
description: |
  Personal Web Site maintains highlights about interesting technologies in
  software development, distributed systems, cloud computing and security.


theme: just-the-docs
remote_theme: fogfish/just-the-docs

search_enabled: true

ga_tracking: UA-78986123-3

aux_links:
  "Twitter":
    - "https://twitter.com/_fogfish_"
  "GitHub":
    - "https://github.com/fogfish"
  "LinkedIn":
    - "https://www.linkedin.com/in/dmkolesnikov/"

twitter:
  username: _fogfish_
  card: summary

social:
  name: fogfish
  links:
    - https://twitter.com/_fogfish_
    - https://github.com/fogfish

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
