title: ğ–â‹…ğ–†ğ–’â‹…ğ–‹ğ–”ğ–Œâ‹…ğ–‹ğ–ğ–˜ğ–
baseurl: ""
url: ""
description: |
  Personal Web Site to share insides about Functional Programming,
  Consumer Internet Services, Distributed Systems, Linked Data, 
  Cloud Services, Security and many other subjects.

theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

search_enabled: true

ga_tracking: UA-78986123-3

aux_links:
  "Twitter":
    - "https://twitter.com/_fogfish_"
  "GitHub":
    - "https://github.com/fogfish"
  "LinkedIn":
    - "https://www.linkedin.com/in/dmkolesnikov/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
